FROM docker.io/library/python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir rns==1.4.2

COPY config.template /opt/reticulum/config.template
COPY entrypoint.sh /usr/local/bin/reticulum-entrypoint
RUN chmod 0755 /usr/local/bin/reticulum-entrypoint && mkdir /data

VOLUME ["/data"]
ENTRYPOINT ["/usr/local/bin/reticulum-entrypoint"]
